// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Data.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Data.Data.Entities.AnnouncementRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AnnouncementId", "UserId")
                        .IsUnique();

                    b.ToTable("AnnouncementReads");
                });

            modelBuilder.Entity("Data.Data.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("LessonId", "StudentId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Data.Data.Entities.AttendanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Obecność",
                            ShortCode = "OB"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Nieobecność",
                            ShortCode = "NB"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Spóźnienie",
                            ShortCode = "SP"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Usprawiedliwione",
                            ShortCode = "U"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Zwolnienie",
                            ShortCode = "ZW"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.BehaviorGradeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("BehaviorGradeRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeName = "Wzorowe",
                            IsActive = true,
                            MaxPoints = 200,
                            MinPoints = 51,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 2,
                            GradeName = "Bardzo dobre",
                            IsActive = true,
                            MaxPoints = 50,
                            MinPoints = 41,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 3,
                            GradeName = "Dobre",
                            IsActive = true,
                            MaxPoints = 40,
                            MinPoints = 31,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 4,
                            GradeName = "Poprawne",
                            IsActive = true,
                            MaxPoints = 30,
                            MinPoints = 21,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 5,
                            GradeName = "Nieodpowiednie",
                            IsActive = true,
                            MaxPoints = 20,
                            MinPoints = 11,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 6,
                            GradeName = "Naganne",
                            IsActive = true,
                            MaxPoints = 10,
                            MinPoints = 0,
                            SchoolYearId = 1
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.BehaviorNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BehaviorNoteTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorNoteTypeId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("BehaviorNotes");
                });

            modelBuilder.Entity("Data.Data.Entities.BehaviorNoteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultPoints")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BehaviorNoteTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultPoints = 5,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Pozytywna"
                        },
                        new
                        {
                            Id = 2,
                            DefaultPoints = -5,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Negatywna"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.CalendarColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CalendarColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "#FF0000",
                            Name = "Czerwony"
                        },
                        new
                        {
                            Id = 2,
                            Code = "#00FF00",
                            Name = "Zielony"
                        },
                        new
                        {
                            Id = 3,
                            Code = "#0000FF",
                            Name = "Niebieski"
                        },
                        new
                        {
                            Id = 4,
                            Code = "#FFFF00",
                            Name = "Żółty"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarEventTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarEventTypeId");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassSubjectId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("Data.Data.Entities.CalendarEventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarColorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarColorId");

                    b.ToTable("CalendarEventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalendarColorId = 1,
                            Name = "Sprawdzian"
                        },
                        new
                        {
                            Id = 2,
                            CalendarColorId = 2,
                            Name = "Kartkówka"
                        },
                        new
                        {
                            Id = 3,
                            CalendarColorId = 3,
                            Name = "Zadanie domowe"
                        },
                        new
                        {
                            Id = 4,
                            CalendarColorId = 4,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Letter = "A",
                            Level = 1,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Letter = "B",
                            Level = 4,
                            SchoolYearId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Letter = "C",
                            Level = 8,
                            SchoolYearId = 1
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.ClassStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassId", "StudentId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("Data.Data.Entities.ClassSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubjects");
                });

            modelBuilder.Entity("Data.Data.Entities.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "101"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "102"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "103"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "104"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "105"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "201"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "202"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "203"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "204"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "205"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "301"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "302"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "303"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "304"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "305"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "gimnastyczna 1"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "gimnastyczna 2"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "aula"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.Excuse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("ParentId");

                    b.ToTable("Excuses");
                });

            modelBuilder.Entity("Data.Data.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("GradeTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeCategoryId");

                    b.HasIndex("GradeTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Data.Data.Entities.GradeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GradeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Sprawdzian",
                            Weight = 3
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Kartkówka",
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Odpowiedź ustna",
                            Weight = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Aktywność",
                            Weight = 1
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Zadanie domowe",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.GradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Numeric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(2,1)");

                    b.HasKey("Id");

                    b.ToTable("GradeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Niedostateczny",
                            Numeric = "1",
                            Value = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Dopuszczający",
                            Numeric = "2",
                            Value = 2.0m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Dostateczny",
                            Numeric = "3",
                            Value = 3.0m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Dobry",
                            Numeric = "4",
                            Value = 4.0m
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Bardzo dobry",
                            Numeric = "5",
                            Value = 5.0m
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Celujący",
                            Numeric = "6",
                            Value = 6.0m
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonHourId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("LessonHourId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Data.Data.Entities.LessonHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("LessonHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeOnly(8, 45, 0),
                            IsActive = true,
                            OrderNumber = 1,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeOnly(9, 40, 0),
                            IsActive = true,
                            OrderNumber = 2,
                            StartTime = new TimeOnly(8, 55, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeOnly(10, 35, 0),
                            IsActive = true,
                            OrderNumber = 3,
                            StartTime = new TimeOnly(9, 50, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeOnly(11, 30, 0),
                            IsActive = true,
                            OrderNumber = 4,
                            StartTime = new TimeOnly(10, 45, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeOnly(12, 30, 0),
                            IsActive = true,
                            OrderNumber = 5,
                            StartTime = new TimeOnly(11, 45, 0)
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeOnly(13, 35, 0),
                            IsActive = true,
                            OrderNumber = 6,
                            StartTime = new TimeOnly(12, 50, 0)
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeOnly(14, 30, 0),
                            IsActive = true,
                            OrderNumber = 7,
                            StartTime = new TimeOnly(13, 45, 0)
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeOnly(15, 25, 0),
                            IsActive = true,
                            OrderNumber = 8,
                            StartTime = new TimeOnly(14, 40, 0)
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeOnly(16, 15, 0),
                            IsActive = true,
                            OrderNumber = 9,
                            StartTime = new TimeOnly(15, 30, 0)
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.LessonStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LessonStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Zaplanowana"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Zrealizowana"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Odwołana"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.ParentStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ParentId", "StudentId")
                        .IsUnique();

                    b.ToTable("ParentStudents");
                });

            modelBuilder.Entity("Data.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Nauczyciel"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Rodzic"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Uczeń"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateOnly(2026, 6, 30),
                            IsActive = true,
                            Name = "2025/2026",
                            StartDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateOnly(2027, 6, 30),
                            IsActive = true,
                            Name = "2026/2027",
                            StartDate = new DateOnly(2026, 9, 1)
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateOnly(2025, 1, 31),
                            IsActive = true,
                            Name = "Semestr 1",
                            SchoolYearId = 1,
                            StartDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateOnly(2025, 6, 30),
                            IsActive = true,
                            Name = "Semestr 2",
                            SchoolYearId = 1,
                            StartDate = new DateOnly(2026, 2, 1)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateOnly(2026, 1, 31),
                            IsActive = true,
                            Name = "Semestr 1",
                            SchoolYearId = 2,
                            StartDate = new DateOnly(2026, 9, 1)
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateOnly(2026, 6, 30),
                            IsActive = true,
                            Name = "Semestr 2",
                            SchoolYearId = 2,
                            StartDate = new DateOnly(2027, 2, 1)
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "matematyka"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "język polski"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "język angielski"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "język niemiecki"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "informatyka"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "wychowanie fizyczne"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "historia"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "WOS"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "biologia"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "chemia"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "fizyka"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Geografia"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "przyroda"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "plastyka"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "muzyka"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "zajęcia artystyczne"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "religia"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "etyka"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "WDŻ"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "technika"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "EDB"
                        });
                });

            modelBuilder.Entity("Data.Data.Entities.TeacherClassSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "ClassId", "SubjectId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("TeacherClassSubjects");
                });

            modelBuilder.Entity("Data.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Data.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Data.Data.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LessonHourId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("LessonHourId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewAnnouncementDetails", b =>
                {
                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_AnnouncementDetails", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewAttendanceDetails", b =>
                {
                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExcused")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnexcused")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_AttendanceDetails", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewBehaviorDetails", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_BehaviorDetails", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewBehaviorGradeSummary", b =>
                {
                    b.Property<string>("CalculatedGradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_BehaviorGradeSummary", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewClassRegister", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ClassRegister", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewClassStudentDetails", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ClassStudentDetails", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewGradeDetails", b =>
                {
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("GradeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_GradeDetails", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewLessonSchedule", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassroomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_LessonSchedule", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewPendingExcuse", b =>
                {
                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExcuseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LessonDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("int");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_PendingExcuses", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewStudentAttendance", b =>
                {
                    b.Property<int>("AbsentCount")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ExcusedCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LateCount")
                        .HasColumnType("int");

                    b.Property<int>("PresentCount")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_StudentAttendanceSummary", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewTeacherClass", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainSubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_TeacherClasses", (string)null);
                });

            modelBuilder.Entity("Data.Data.EntitiesForView.ViewUpcomingEvent", b =>
                {
                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_UpcomingEvents", (string)null);
                });

            modelBuilder.Entity("Data.Data.Entities.Announcement", b =>
                {
                    b.HasOne("Data.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Data.Data.Entities.AnnouncementRead", b =>
                {
                    b.HasOne("Data.Data.Entities.Announcement", "Announcement")
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Data.Entities.Attendance", b =>
                {
                    b.HasOne("Data.Data.Entities.AttendanceType", "AttendanceType")
                        .WithMany()
                        .HasForeignKey("AttendanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceType");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Data.Data.Entities.BehaviorGradeRange", b =>
                {
                    b.HasOne("Data.Data.Entities.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Data.Data.Entities.BehaviorNote", b =>
                {
                    b.HasOne("Data.Data.Entities.BehaviorNoteType", "BehaviorNoteType")
                        .WithMany()
                        .HasForeignKey("BehaviorNoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BehaviorNoteType");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Data.Data.Entities.CalendarEvent", b =>
                {
                    b.HasOne("Data.Data.Entities.CalendarEventType", "CalendarEventType")
                        .WithMany()
                        .HasForeignKey("CalendarEventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("Data.Data.Entities.ClassSubject", "ClassSubject")
                        .WithMany()
                        .HasForeignKey("ClassSubjectId");

                    b.Navigation("CalendarEventType");

                    b.Navigation("Class");

                    b.Navigation("ClassSubject");
                });

            modelBuilder.Entity("Data.Data.Entities.CalendarEventType", b =>
                {
                    b.HasOne("Data.Data.Entities.CalendarColor", "CalendarColor")
                        .WithMany()
                        .HasForeignKey("CalendarColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarColor");
                });

            modelBuilder.Entity("Data.Data.Entities.Class", b =>
                {
                    b.HasOne("Data.Data.Entities.SchoolYear", "SchoolYear")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Data.Data.Entities.ClassStudent", b =>
                {
                    b.HasOne("Data.Data.Entities.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Data.Data.Entities.ClassSubject", b =>
                {
                    b.HasOne("Data.Data.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Data.Data.Entities.Excuse", b =>
                {
                    b.HasOne("Data.Data.Entities.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Data.Data.Entities.Grade", b =>
                {
                    b.HasOne("Data.Data.Entities.GradeCategory", "GradeCategory")
                        .WithMany()
                        .HasForeignKey("GradeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.GradeType", "GradeType")
                        .WithMany()
                        .HasForeignKey("GradeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradeCategory");

                    b.Navigation("GradeType");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Data.Data.Entities.Lesson", b =>
                {
                    b.HasOne("Data.Data.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.LessonHour", "LessonHour")
                        .WithMany()
                        .HasForeignKey("LessonHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.LessonStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Classroom");

                    b.Navigation("LessonHour");

                    b.Navigation("Status");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Data.Data.Entities.ParentStudent", b =>
                {
                    b.HasOne("Data.Data.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Data.Data.Entities.Semester", b =>
                {
                    b.HasOne("Data.Data.Entities.SchoolYear", "SchoolYear")
                        .WithMany("Semesters")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Data.Data.Entities.TeacherClassSubject", b =>
                {
                    b.HasOne("Data.Data.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Data.Data.Entities.UserRole", b =>
                {
                    b.HasOne("Data.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Data.Entities.WeeklySchedule", b =>
                {
                    b.HasOne("Data.Data.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.LessonHour", "LessonHour")
                        .WithMany()
                        .HasForeignKey("LessonHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Data.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Classroom");

                    b.Navigation("LessonHour");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Data.Data.Entities.Class", b =>
                {
                    b.Navigation("ClassStudents");
                });

            modelBuilder.Entity("Data.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Data.Data.Entities.SchoolYear", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("Data.Data.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
